/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HarngunnaImport } from './routes/harngunna'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HarngunnaRoute = HarngunnaImport.update({
  id: '/harngunna',
  path: '/harngunna',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/harngunna': {
      id: '/harngunna'
      path: '/harngunna'
      fullPath: '/harngunna'
      preLoaderRoute: typeof HarngunnaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harngunna': typeof HarngunnaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harngunna': typeof HarngunnaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/harngunna': typeof HarngunnaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harngunna'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harngunna'
  id: '__root__' | '/' | '/harngunna'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarngunnaRoute: typeof HarngunnaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarngunnaRoute: HarngunnaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/harngunna"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/harngunna": {
      "filePath": "harngunna.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
